"""
Convert a TFLite model binary to a C/C++ source file (.cc) and header (.h).

The generated files are compatible with TensorFlow Lite for Microcontrollers
(TFLM) / Arduino / ESP32 / STM32 embedded workflows.
"""

import pathlib
import textwrap


def tflite_to_c_array(
    tflite_path: str,
    output_cc: str,
    output_h: str | None = None,
    array_name: str = "g_person_detect_model_data",
    align: int = 16,
    cols: int = 12,
) -> str:
    """
    Read *tflite_path* and write a C source file containing the model bytes.

    Parameters
    ----------
    tflite_path : path to the .tflite binary
    output_cc   : path for the generated .cc file
    output_h    : path for the generated .h file (None = skip)
    array_name  : C identifier for the byte array
    align       : __attribute__((aligned(...))) value (must be ≥ 4)
    cols        : hex bytes per line

    Returns
    -------
    The C source as a string (also written to output_cc).
    """
    data = pathlib.Path(tflite_path).read_bytes()
    n    = len(data)

    # ── Build hex body ────────────────────────────────────────────────────────
    hex_bytes = [f"0x{b:02x}" for b in data]
    lines     = []
    for i in range(0, n, cols):
        chunk = hex_bytes[i : i + cols]
        lines.append("  " + ", ".join(chunk) + ("," if i + cols < n else ""))
    hex_body = "\n".join(lines)

    # ── .cc source ────────────────────────────────────────────────────────────
    cc_src = textwrap.dedent(f"""\
        // Auto-generated by c_array.py – do not edit.
        // Source: {tflite_path}
        // Size  : {n} bytes

        #include "{pathlib.Path(output_h or output_cc).stem}.h"

        // Model data aligned for DMA / SIMD access.
        __attribute__((aligned({align})))
        const unsigned char {array_name}[] = {{
        {hex_body}
        }};

        const unsigned int {array_name}_len = {n}U;
    """)

    # ── .h header ────────────────────────────────────────────────────────────
    guard = (array_name.upper() + "_H_")
    h_src = textwrap.dedent(f"""\
        // Auto-generated by c_array.py – do not edit.
        #ifndef {guard}
        #define {guard}

        extern const unsigned char {array_name}[];
        extern const unsigned int  {array_name}_len;

        #endif  // {guard}
    """)

    # ── Write files ───────────────────────────────────────────────────────────
    pathlib.Path(output_cc).parent.mkdir(parents=True, exist_ok=True)
    pathlib.Path(output_cc).write_text(cc_src)
    print(f"[c_array] wrote {output_cc}  ({n} bytes → {n} hex entries)")

    if output_h is not None:
        pathlib.Path(output_h).write_text(h_src)
        print(f"[c_array] wrote {output_h}")

    # ── Pretty-print snippet ──────────────────────────────────────────────────
    preview_lines = hex_bytes[:cols]
    print(f"\n[c_array] first {len(preview_lines)} bytes preview:")
    print("  " + ", ".join(preview_lines) + ", …")

    return cc_src
