// Auto-generated by c_array.py – do not edit.
#ifndef G_PERSON_DETECT_MODEL_DATA_H_
#define G_PERSON_DETECT_MODEL_DATA_H_

extern const unsigned char g_person_detect_model_data[];
extern const unsigned int  g_person_detect_model_data_len;

#endif  // G_PERSON_DETECT_MODEL_DATA_H_
