// Auto-generated by c_array.py – do not edit.
#ifndef PERSON_DETECT_MODEL_DATA_H_
#define PERSON_DETECT_MODEL_DATA_H_

extern const unsigned char person_detect_model_data[];
extern const unsigned int  person_detect_model_data_len;

#endif  // PERSON_DETECT_MODEL_DATA_H_
